"""
gen_iata_routes.py
──────────────────
Downloads the OpenFlights routes dataset (~67k worldwide
commercial routes), filters it to airports that exist in our
airports.js, and writes a fresh iata_routes.js covering NRT,
HND, JFK, DXB, etc.  — instead of just the European subset.

Usage:
    python gen_iata_routes.py

Output:
    ../flights/iata_routes.js   (overwrites the Europe-only version)

OpenFlights is a community-maintained public-domain dataset.
It's a few years behind on brand-new routes but it's the
broadest open baseline available.
"""

import re
import csv
import io
import urllib.request
import pathlib

ROOT          = pathlib.Path(__file__).resolve().parent
AIRPORTS_JS   = ROOT.parent / "flights" / "airports.js"
OUT_FILE      = ROOT.parent / "flights" / "iata_routes.js"

OPENFLIGHTS_URL = (
    "https://raw.githubusercontent.com/jpatokal/"
    "openflights/master/data/routes.dat"
)

# ── Step 1: extract all known IATA codes from airports.js ────────────────
print("Reading airports.js ...")
airports_text = AIRPORTS_JS.read_text(encoding="utf-8")
known_iatas   = set(re.findall(r'"iata":\s*"([A-Z]{3})"', airports_text))
print(f"  Found {len(known_iatas)} IATA codes in airports.js")

# ── Step 2: download OpenFlights routes.dat ──────────────────────────────
print(f"Downloading OpenFlights routes from {OPENFLIGHTS_URL} ...")
try:
    with urllib.request.urlopen(OPENFLIGHTS_URL, timeout=30) as resp:
        raw_csv = resp.read().decode("utf-8", errors="replace")
    print(f"  Downloaded {len(raw_csv):,} bytes")
except Exception as e:
    raise SystemExit(f"  ERROR downloading: {e}")

# ── Step 3: parse routes ─────────────────────────────────────────────────
# routes.dat columns (no header):
#   0  Airline
#   1  Airline ID
#   2  Source airport (IATA)
#   3  Source airport ID
#   4  Destination airport (IATA)
#   5  Destination airport ID
#   6  Codeshare
#   7  Stops
#   8  Equipment
print("Parsing routes ...")
reader = csv.reader(io.StringIO(raw_csv))
routes_map = {}         # src_iata -> set of dest IATAs
n_total     = 0
n_kept      = 0
n_nondirect = 0

for row in reader:
    n_total += 1
    if len(row) < 8:
        continue
    src   = row[2].strip().upper()
    dst   = row[4].strip().upper()
    stops = row[7].strip()

    # Only 3-letter IATA codes
    if len(src) != 3 or len(dst) != 3:
        continue
    if not src.isalpha() or not dst.isalpha():
        continue
    if src == dst:
        continue
    # Only nonstop routes
    if stops not in ("0", ""):
        n_nondirect += 1
        continue
    # Must be airports we know about
    if src not in known_iatas or dst not in known_iatas:
        continue

    routes_map.setdefault(src, set()).add(dst)
    n_kept += 1

print(f"  Total rows seen   : {n_total:,}")
print(f"  Non-direct skipped: {n_nondirect:,}")
print(f"  Routes kept       : {n_kept:,}")
print(f"  Unique origins    : {len(routes_map):,}")

# ── Spot-check some major hubs ───────────────────────────────────────────
hubs = ["NRT", "HND", "PEK", "JFK", "LAX", "DXB", "SYD", "GRU", "SIN", "BKK",
        "ICN", "DEL", "BOM", "MAD", "BCN", "LHR", "CDG", "FRA"]
print("  Hub coverage:")
for h in hubs:
    n = len(routes_map.get(h, ()))
    print(f"    {h}: {n} destinations")

# ── Step 4: write iata_routes.js ─────────────────────────────────────────
print(f"Writing {OUT_FILE} ...")

lines = []
lines.append("/* ---------------------------------------------------------------")
lines.append("   WORLDWIDE IATA ROUTES")
lines.append("   Static lookup: ORIGIN_IATA -> [DESTINATION_IATA, ...]")
lines.append("")
lines.append(f"   Auto-generated by gen_iata_routes.py")
lines.append(f"   Source: OpenFlights routes.dat (community, public domain)")
lines.append(f"   Routes are nonstop only (stops=0).")
lines.append(f"   {len(routes_map):,} origin airports - {n_kept:,} routes total")
lines.append("--------------------------------------------------------------- */")
lines.append("var IATA_ROUTES = {")

for src in sorted(routes_map.keys()):
    dests = sorted(routes_map[src])
    lines.append(f'  "{src}": [')
    for d in dests:
        lines.append(f'    "{d}",')
    lines.append("  ],")

lines.append("};")
lines.append("")

OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"  Done - {OUT_FILE.stat().st_size:,} bytes written.")
print()
print("OK - iata_routes.js regenerated with worldwide coverage.")
