"""
gen_airport_coords.py
─────────────────────
Downloads the OurAirports public-domain CSV (~70 k airports),
cross-references it with every IATA code in airports.js, and
writes a new airport_coords.js covering ALL airports worldwide.

Usage:
    python gen_airport_coords.py

Output:
    ../flights/airport_coords.js   (overwrites the Europe-only version)
"""

import json
import re
import csv
import io
import urllib.request
import pathlib

# ── Paths ──────────────────────────────────────────────────────────────────
ROOT          = pathlib.Path(__file__).resolve().parent
AIRPORTS_JS   = ROOT.parent / "flights" / "airports.js"
OUT_FILE      = ROOT.parent / "flights" / "airport_coords.js"
OURAIRPORTS_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"

# ── Step 1: extract all IATA codes from airports.js ────────────────────────
print("Reading airports.js …")
airports_text = AIRPORTS_JS.read_text(encoding="utf-8")
# Pull every "iata": "XXX" value
iata_codes = set(re.findall(r'"iata":\s*"([A-Z]{3})"', airports_text))
print(f"  Found {len(iata_codes)} IATA codes in airports.js")

# ── Step 2: download OurAirports CSV ───────────────────────────────────────
print(f"Downloading OurAirports data from {OURAIRPORTS_URL} …")
try:
    with urllib.request.urlopen(OURAIRPORTS_URL, timeout=30) as resp:
        raw_csv = resp.read().decode("utf-8")
    print(f"  Downloaded {len(raw_csv):,} bytes")
except Exception as e:
    print(f"  ERROR downloading: {e}")
    print("  Trying fallback URL …")
    fallback = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/airports.csv"
    with urllib.request.urlopen(fallback, timeout=30) as resp:
        raw_csv = resp.read().decode("utf-8")
    print(f"  Downloaded {len(raw_csv):,} bytes from fallback")

# ── Step 3: parse CSV and build IATA → {lat, lon} ──────────────────────────
print("Parsing CSV …")
reader = csv.DictReader(io.StringIO(raw_csv))
coords_map = {}   # iata → (lat, lon)

for row in reader:
    iata = (row.get("iata_code") or "").strip().upper()
    if not iata or len(iata) != 3:
        continue
    try:
        lat = round(float(row["latitude_deg"]),  4)
        lon = round(float(row["longitude_deg"]), 4)
    except (KeyError, ValueError):
        continue
    # OurAirports may have duplicates; prefer the one with a real IATA
    if iata not in coords_map:
        coords_map[iata] = (lat, lon)

print(f"  Parsed {len(coords_map):,} IATA codes with coordinates")

# ── Step 4: intersect with our airports list ───────────────────────────────
matched   = {}
missing   = []
for code in sorted(iata_codes):
    if code in coords_map:
        matched[code] = coords_map[code]
    else:
        missing.append(code)

print(f"  Matched : {len(matched):,}")
more = "..." if len(missing) > 20 else ""
print(f"  Missing : {len(missing):,}  ->  {missing[:20]}{more}")

# ── Step 5: write airport_coords.js ────────────────────────────────────────
print(f"Writing {OUT_FILE} …")

lines = []
lines.append("/* ---------------------------------------------------------------")
lines.append("   WORLDWIDE AIRPORT COORDINATES")
lines.append("   Static lookup: IATA → { lat, lon }")
lines.append("")
lines.append(f"   Auto-generated by gen_airport_coords.py")
lines.append(f"   Source: OurAirports (public domain) – ourairports.com")
lines.append(f"   Covers all {len(matched):,} airports present in airports.js")
lines.append(f"   that have coordinates in the OurAirports dataset.")
lines.append("--------------------------------------------------------------- */")
lines.append("const AIRPORT_COORDS = {")

# Group by country prefix (cosmetic only)
# Re-read airports.js entries so we can annotate country headings
country_re = re.compile(r'//\s*--\s*([A-Z]{2})\s*--')
iata_re     = re.compile(r'"iata":\s*"([A-Z]{3})"')
current_country = None
output_entries  = []

for line in airports_text.splitlines():
    cm = country_re.search(line)
    if cm:
        current_country = cm.group(1)
        continue
    im = iata_re.search(line)
    if im:
        iata = im.group(1)
        if iata in matched:
            output_entries.append((current_country or "??", iata, matched[iata]))

# Now emit, grouped by country
from itertools import groupby
output_entries.sort(key=lambda x: (x[0], x[1]))

current = None
for country, iata, (lat, lon) in output_entries:
    if country != current:
        if current is not None:
            lines.append("")
        lines.append(f"  // ── {country} ──")
        current = country
    lines.append(f'  "{iata}": {{ lat: {lat:>10.4f}, lon: {lon:>10.4f} }},')

lines.append("};")
lines.append("")

OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"  Done – {OUT_FILE.stat().st_size:,} bytes written.")
print()
print("OK - airport_coords.js updated. Now remove the European filter in geo.js.")
